/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaoop;

public class User {

    private String Name;
/*    public user (String Name){
        this.Name = Name;
    }*/ 

    public void setName(String Name){
        this.Name = Name;
    }

    public String getName() {
        return Name;
    }

    public String getPhoneNo() {
        switch (Name) {
            case "Jane":
                return "08123456789";
        
            case "John":
                return "07012345678";

            case "Ezra":
                return "09066773426";

            default:
                return "No Record foud for name";
        }
    }
}